# Generated by Django 5.0.3 on 2024-03-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('grade', models.CharField(max_length=5, verbose_name='Grade')),
            ],
        ),
    ]
