# Generated by Django 5.0.3 on 2024-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_data', '0002_student_isgraduate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Birthdate'),
        ),
    ]
